### PR TITLE
Add ci pipeline to the project

### PR DESCRIPTION
**Pull request by pacoorozco**
## TL;TR;
I've added a basic CI pipeline to the project. I'm going to iterate over it in order to add testing and automatic releasing.
All the process could be done locally using the `Makefile`:
```
$ make
clean                          Clean all built artifacts
help                           Show this help.
lint                           Run linter
release                        Create binaries for all supported platforms
test                           Run tests
```
## Run tests
There is no test yet, but you can run them using:
```
$ make test
```
## Generate binaries
You can generate platform specific binaries, setting the `VERSION` using:
```
$ make VERSION=0.2.1 release
```
## CI pipeline
We are using Travis to run tests and generate binaries. In next iteration we are going to use that to publish binaries automatically.

Related with #1

### CODE REVIEW

**Comment by pacoorozco** [comment]
I have a new PR to enable linting on this project

**Comment by nmrshll** [comment]
Looks like great work. However I get this error on every make command:
`Makefile:42: *** target pattern contains no '%'.  Stop.`

It seems to be related to those lines:
```
BIN_DIR := $(GOPATH)/bin
GOMETALINTER := $(BIN_DIR)/gometalinter

$(GOMETALINTER):
	@echo "--> Installing gometalinter..."
	@go get -u github.com/alecthomas/gometalinter
	@gometalinter --install &> /dev/null
```

I suspect the problem might be for go installations with several GOPATHs like I have:
`$ echo $GOPATH`: `/home/me/.cache/go:/home/me`

Do you have a clue how to fix this ?

**Comment by pacoorozco** [comment]
I've patched the `Makefile` in order to use the first path in `GOPATH`. If I'm not wrong it's the proper way to use it in multiple paths.

Can you test it?

**Comment by nmrshll** [comment]
I'll definitely test that first thing tomorrow ! Thanks !

**Comment by pacoorozco** [comment]
@nmrshll , have you test it? I'd like to merge this one and CI linter/testing after this

**Comment by nmrshll** [comment]
love it ! Thanks a lot ! I'm merging it

**Pull request merged**
