### PR TITLE
docs: update install path.

### PR DESCRIPTION
**Pull request by appleboy**
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by pacoorozco** [comment]
Good job @appleboy ! In some days we are going to be able to release the binary directly...

**Comment by pacoorozco** [comment]
Trying to use `go get -u github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli` still fail giving an error:
```
$ go get -u github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli
go: cannot find main module; see 'go help modules'
```

**Comment by pacoorozco** [comment]
Working now! Thanks!

**Comment by appleboy** [comment]
@nmrshll Could you merge this changes?

**Comment by nmrshll** [comment]
@appleboy absolutely !

**Pull request merged**
