### PR TITLE
fix mixmatched type files.go issue #38

### PR DESCRIPTION
**Pull request by tonymet**
fix issue #38

### CODE REVIEW

**Comment by tonymet** [comment]
tests look ok. did a test run and it was ok too
## Test Results
```
--> Running tests...
?   	github.com/nmrshll/gphotos-uploader-cli/cmd/gphotos-uploader-cli	[no test files]

=== RUN   TestInitAndLoadConfig
=== RUN   TestInitAndLoadConfig/TestInitConfigFile
=== RUN   TestInitAndLoadConfig/TestLoadConfigFile
--- PASS: TestInitAndLoadConfig (0.00s)
    --- PASS: TestInitAndLoadConfig/TestInitConfigFile (0.00s)
    --- PASS: TestInitAndLoadConfig/TestLoadConfigFile (0.00s)
PASS
ok  	github.com/nmrshll/gphotos-uploader-cli/config	0.014s
?   	github.com/nmrshll/gphotos-uploader-cli/datastore/completeduploads	[no test files]
?   	github.com/nmrshll/gphotos-uploader-cli/datastore/tokenstore	[no test files]
?   	github.com/nmrshll/gphotos-uploader-cli/fileshandling	[no test files]
?   	github.com/nmrshll/gphotos-uploader-cli/upload	[no test files]
?   	github.com/nmrshll/gphotos-uploader-cli/utils/filesystem	[no test files]
```

**Comment by tonymet** [comment]
@nmrshll Can I get your help merging this one?

**Comment by nmrshll** [comment]
Looks good to me ! Thanks for jumping in !

**Comment by tonymet** [comment]
@nmrshll thanks a lot for this app it was a huge help for me. I'm happy to help out.  gphotos-uploader really helped me with a large project so thanks a ton 👍

**Pull request merged**
