### PR TITLE
Support 5 concurrent uploads. Reduce API calls. Speed things up

### PR DESCRIPTION
**Pull request by tonymet**
## Benefits
* double upload throughput
* reduce API calls by 30% to allow 3k more uploads within 10000 daily quota
* uses `const uploadConcurrency = 5` to set concurrency

## Example Run
```
2019/01/28 22:44:21 Uploading DSC_0018.JPG
2019/01/28 22:44:22 Uploading DSC_0020.JPG
2019/01/28 22:44:22 Uploading DSC_0017.JPG
2019/01/28 22:44:22 Uploading DSC_0016.JPG
2019/01/28 22:44:22 Uploading DSC_0019.JPG
2019/01/28 22:44:28 DSC_0018.JPG uploaded successfully asxxxxxxRkquFB8zLGg6tXyA
2019/01/28 22:44:28 Marked as uploaded: xxxxx
2019/01/28 22:44:29 DSC_0016.JPG uploaded successfully as xxxxxx
2019/01/28 22:44:29 Marked as uploaded: xxxxxxx
2019/01/28 22:44:29 DSC_0017.JPG uploaded xxxxxxx
2019/01/28 22:44:29 Marked as uploaded: xxxxxxx
2019/01/28 22:44:30 DSC_0020.JPG uploaded successfully as Axxxxxx
2019/01/28 22:44:30 Marked as uploaded: xxxxxx
2019/01/28 22:44:30 DSC_0019.JPG uploaded successfully as xxxxx
```

## time feature/concurrent
upload 10 images **26.6s total**
```
time go run cmd/gphotos-uploader-cli/main.go
[TRUNCATED]
go run cmd/gphotos-uploader-cli/main.go  1.11s user 0.52s system 6% cpu 25.676 total
```

## time origin/master
upload 10 images **53s total**
```
time go run cmd/gphotos-uploader-cli/main.go
[TRUNCATED]
go run cmd/gphotos-uploader-cli/main.go  1.20s user 0.56s system 3% cpu 53.020 total
```

### CODE REVIEW

**Comment by driv** [comment]
I see you're storing the album, instead of the name. This should help with https://github.com/nmrshll/gphotos-uploader-cli/issues/19 , right?

**Comment by tonymet** [comment]
yes that's correct

**Comment by driv** [comment]
Seems to work nicely, just 2 small things.

- It looks like it's uploading too fast since I'm getting:
````
0521-a94d2fbcfb40/lib-gphotos/client.go:115 (Client.UploadFile) ---
Caused by: googleapi: Error 429: Quota exceeded for quota metric 'photoslibrary.googleapis.com/write_requests' and limit 'WritesPerMinutePerUser' of service 'photoslibrary.googleapis.com' for consumer 'project_number:000000000000'., rateLimitExceeded
````
- The album should be created on the first upload, not before, new albums are being created for directories in which all files were skipped and empty directories.

**Comment by tonymet** [comment]
@driv Thanks for the awesome feedback i appreciate the testing. google does respond with flow control i'll see if I can add that. 

For the album-creation-let me look into a graceful way to do that. 

thanks again for the feedback

**Comment by tonymet** [comment]
@driv I was able to address the 429 issue on `v1/upload` by refactoring the retry logic to cover that as well.  Can you please test?  

Alas, will need to pull nmrshll/google-photos-api-client-go/pull/3 (the retry logic is in a separate package / git repo

here's a quick way to do that

```
 cd $GOPATH/src/github.com/nmrshll/google-photos-api-client-go
 git remote add tonymet git@github.com:tonymet/google-photos-api-client-go.git
 git fetch tonymet
 git checkout feature/retry-media-upload
 # at this point you can build
```

**Comment by norbusan** [comment]
Just to report that with this pull request upload and generation of albums works correctly! The only problem I see at the moment is that it hits the upload limits rather soon. Thanks a lot!

**Comment by tonymet** [comment]
@norbusan Thanks for the report very helpful!  Those limits can be resolved by using  `nmrshll/google-photos-api-client-go/pull/3 ` -- i put some directions above.

**Comment by tonymet** [comment]
@driv have you tried the branch I created above to test the upload limits?

**Comment by driv** [comment]
No, I've been on vacation without my computer and couldn't give it a go.

**Comment by norbusan** [comment]
@tonymet thanks, I tried that by pulling it into my working branch and rebuilding the cli (cli has this PR, too). I still get errors, I guess this is now from the project id:
```
 --- at /home/norbert/go/src/github.com/nmrshll/google-photos-api-client-go/lib-gphotos/client.go:207 (Client.UploadFile) ---
Caused by: googleapi: Error 429: Quota exceeded for quota metric 'photoslibrary.googleapis.com/all_requests' and limit 'ApiCallsPerProjectPerDay' of service 'photoslibrary.googleapis.com' for consumer 'project_number:20637643488'., rateLimitExceeded
```

**Comment by tonymet** [comment]
If you hit `ApiCallsPerProjectPerDay` you will have to wait 24hrs to reset.

The new branch will help with that tomorrow, as it uses fewer api calls per
upload.  And it helps with the throughput quota as well (once your daily
resets tmr).

**Comment by norbusan** [comment]
@tonymet thanks for the explanation, but what makes me also nervous is the `limit 'ApiCallsPerProjectPerDay'` There is a project number in my configuration file I have no idea where it came from ;-)

**Comment by tonymet** [comment]
@norbusan you can see the active quotas on the project here :
replace `PROJECT_ID` with yours
 https://console.cloud.google.com/iam-admin/quotas?project=PROJECT_ID&authuser=0

**Comment by norbusan** [comment]
Interestingly, I get
```
You don't have permissions to perform the action on the selected resource. 
```

**Comment by deselaers** [comment]
This works well for me - would be great to get this merged.

**Comment by nook-ru** [comment]
@tonymet, still getting Error 429 even with https://github.com/nmrshll/google-photos-api-client-go/pull/3 changes

```
2019/04/10 21:35:46 Uploading IMG_6706.JPG
2019/04/10 21:35:46 Rate limit reached, sleeping for 0 seconds...
2019/04/10 21:35:46 Rate limit reached, sleeping for 0 seconds...
2019/04/10 21:35:46 Rate limit reached, sleeping for 0 seconds...
2019/04/10 21:35:46 failed uploading image: failed uploading image: failed adding media IMG_6705.JPG
 --- at /home/nook/GolandProjects/google-photos-api-client-go/lib-gphotos/client.go:207 (Client.UploadFile) ---
Caused by: googleapi: Error 429: Quota exceeded for quota metric 'photoslibrary.googleapis.com/write_requests' and limit 'WritesPerMinutePerUser' of service 'photoslibrary.googleapis.com' for consumer 'project_number:20637643488'., rateLimitExceeded
```

Seems like there is no header passed into `parse429Header`:

<details>
  <summary>debugger screenshot</summary>
  image
</details>

**Pull request merged**
