### PR TITLE
Store uploaded image hashes in a LevelDB to prevent re-uploads

### PR DESCRIPTION
**Pull request by nhorvath**
Use a LevelDB key value store to keep track up previously uploaded images.
https://github.com/syndtr/goleveldb

I'm new to programming in Go so if you have a better storage solution feel free to change it or let me know.

Improvement towards achieving https://github.com/nmrshll/gphotos-uploader-cli/issues/12

### CODE REVIEW

**Comment by nmrshll** [comment]
Well my bad really, I didn't document that part of the code properly, I didn't really expect the stars and PRs

**Comment by nmrshll** [comment]
@nhorvath Is there a particular reason you included the last modified time in the cache key ?

**Comment by nhorvath** [comment]
Stat was way faster than hash. I have tens of thousands of pictures I tried
to upload and it takes forever to go through. It uses mtime first and if
that's different it uses hash.

**Comment by nmrshll** [comment]
Thanks, that's the kind of thing I wasn't sure of
Just asking to avoid going through the same steps and getting to the same conclusion

**Comment by nhorvath** [comment]
See my stream of consciousness here for explanations of tweaks to your changes: https://github.com/nhorvath/gphotos-uploader-cli/pull/1

**Comment by nhorvath** [comment]
@nmrshll I think I'm happy with the current state of this branch now. It gets through my files quickly and now works with large movie files. Memory usage now stays low (previously I was seeing like 4GB ram used).

**Comment by cirrusflyer** [comment]
Sorry for the noob question, but am I to understand that this has been implemented and it'll now just upload new photos and not reupload every time?

**Comment by nhorvath** [comment]
yes

**Pull request merged**
