### PR TITLE
Add unit test to config package

### PR DESCRIPTION
**Pull request by pacoorozco**
I've needed to do some refactors in order to make code more testable. 

It's covering 100% of code.

Related with #2 and #1

### CODE REVIEW

**Comment by nmrshll** [comment]
Looks good, could you pull the latest master into both your new PRs ?

**Comment by pacoorozco** [comment]
@nmrshll PR is merged.

**Comment by pacoorozco** [comment]
Can you merge it @nmrshll ?

**Comment by nmrshll** [comment]
Sure ! Sorry for the long delay

**Pull request merged**
