### PR TITLE
add support for videos

### PR DESCRIPTION
**Pull request by Visgean**

### CODE REVIEW

**Comment by barkside** [comment]
This looks good - was wondering where video support was

**Comment by barkside** [comment]
Also need to check the Mime type "video" towards end of IsImage() in file.go

**Comment by nhorvath** [comment]
You should also add mkv

**Comment by nmrshll** [comment]
fixed in #24

Also I now detect the mimetype of the file based on contents rather than on the file extension, that way I don't have to list all the odd extensions out there.

> Also need to check the Mime type "video" towards end of IsImage() in file.go

@barkside absolutely, this is how things are handled now
@Visgean I did the changes in another PR (#24) for that reason

**Comment by nmrshll** [comment]
> You should also add mkv

mkv files should now be detected by the mimetype detection package

**Comment by nmrshll** [comment]
Is everyone all right for me to close this PR ?

**Pull request closed without merging**
