### PR TITLE
Add automatic releases for linux, darwin and snap

### LINKED ISSUE #1: add CI pipeline for testing / building / releasing deb/snap/homebrew/... packages (to drop the dependency on go for installing)

### PR DESCRIPTION
**Pull request by pacoorozco**
# Description
I've included [goreleaser](https://goreleaser.com/) to publish artefacts to GitHub and Snapd.

*Note:* There are some steps that @nmrshll should follow to allow artefacts publishing.

## How to allow artefacts publishing

1. Obtain a GitHub personal access token (with `repo` scope/permission) following [this guide](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/). ***Keep this token safe.***
1. Add this token (***encrypted***) to `.travis.yml`. Using Travis CLI:
    ```
    $ travis encrypt GITHUB_TOKEN="<YOUR TOKEN GOES HERE>" --add
    ```
1. Next you need to export a Snapcraft token that can upload this to Snap. ***This will create a `snap.login` file and DO NOT COMMIT IT***. Execute:
    ```
    $ snapcraft export-login snap.login
    ```
1. Now, you need to encrypt this file to add it to `.travis.yml`. Once again, using Travis CLI:
    ```
    $ travis encrypt-file snap.login --add
    ```
1. ***Remove snap.login***.
1. Commit the `.travis.yml` file to the repository.

All work is done!

## How can I publish a new version?

Every time you create a tag, a new version will be released. To see which tag was the last one:
```
$ git tag -l
v0.1.0
v0.1.11
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
```
Now select you next tag accordingly to [SemVer](https://semver.org/), and tag it:
```
$ git tag v0.1.12 -m "Version 0.1.12"
$ git push origin v0.1.12
```

Fixes #1

### CODE REVIEW

**Comment by nmrshll** [comment]
Travis is giving me headaches.
When I try the last command to encrypt the snap.login file, I get:

```
me@Nicolas-Lenovo-Flex2-15:~/src/github.com/nmrshll/gphotos-uploader-cli$ snap run travis encrypt-file snap.login --add
encrypting snap.login for nmrshll/gphotos-uploader-cli
storing result as snap.login.enc
storing secure env variables for decryption
not logged in - try running travis login --org
```

Even after logging in reports a success, it still tells me I'm not logged in when trying the command above.

Ever seen this problem @pacoorozco ?
Thanks

**Comment by pacoorozco** [comment]
I deleted by mistake

**Comment by pacoorozco** [comment]
Hi @nmrshll 

Do you need any help with that, if you merge and complete this PR, #56 will be solved aswell.

Paco

**Comment by pacoorozco** [comment]
Hi  @nmrshll 

Do you mind if I configure everything with my username? Or if you prefer we can do a pair programming session

Paco

**Pull request merged**
